# Generated by Django 3.0.5 on 2020-04-15 14:14

from django.db import migrations
from quality.download_and_load import download_and_load

def download_2018(apps, schema_editor):
    download_urls = [
        'https://datos.madrid.es/egob/catalogo/201200-10306314-calidad-aire-horario.zip'
    ]

    for url in download_urls:
        download_and_load(url)


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(download_2018),
    ]
